import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import "../styles/globals.css";
export const metadata = {
  title: "KQ-Blogging",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
